script:
  - bash ./deploy.sh
env:
  global:

    - GITHUB_REPO: "jhergon/jhergon.github.io"
    - secure: MIRJbmquSX8CkfBlZ0VP3D3hWKNvpYKrmsx3tHPX7PO+6/MpOGfQ7c1D73ER/TtJ93vtPn368CG0FmqOm4ns+WzILuI11w/JwVolVUhHmHIOZJ6AkxI+diVQO48qTK8p7oGs5h82SmDo0sz/Vk+0zamBjFnnS44mzgTZfzSKngYINdx6JPWMGp/zj1pJFWLG3kSGMZ4Hxf5N+xCNZ99l1nl2qpsfO4YF9IbIEo2jft+ctHpavCA1q7C3CaxJElFFmN4rv5w9InVajnydjmZ84vcd5yEIxWmQXvOBbvcVaUdI6pqGdtYODmeEZU2KlA2YdAIdMeaDr4BmAG3+P/bYkXf9h+MhJCKP834gY5VOZB1N0sSiC1hoaVdTSRzCNkbp0mjTPVo98bC1lO5wJTUNk9fb3m8n0DePoFVR6DhCEjkuDz+rSoCG13+Z3N0eHcG/UzdTdORFXPWOv/6VTV2DQR7HrRS007LXM2hivGDubY/BRtfQ+qkuDSabGdqzeOf0Tf/jTLV1Ee+RFemPezET2JJRV4m0haxpF38ieVYq+B5+F14sAd+/MNIAd2jGf4mcZyhG7nDPYC0I4EUYIOPK8IXwCPlUWZfBZgKsRyymDfm1UYctqA/BQbInA0gYDBk2Yli0B+MMrakWpbg2eyfWDDRvJJvozahImr5QFgly1so=

